[package]
name = "api_2048"
version = "0.1.0"
edition = "2024"

[dependencies]
#atrium-crypto = "0.1.2"
#rand = "0.8.5"
dropshot = "0.16.0"
http = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
tokio = "1.44.2"
schemars = { version = "0.8.22", features = ["uuid1"] }
toml = "0.8.22"
